name: dictionary
description: The ODW DICOM Data Dictionary Library
version: 0.5.1
authors:
  - Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/dictionary

environment:
  sdk: ^1.0.0

dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.5.2

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test: ^0.12.0

